### ISSUE TITLE
how to  finetune for object detection

### ISSUE THREAD

**Issue by turmamat** [CupidJay/Scaled-down-self-supervised-learning#3]
Do you freeze the weight of the pre-training model based on the object detection? I checked your code. There is no blocking in the code.

**Comment by CupidJay** [comment]
Sorry for the late reply. We didn't freeze the weight of the pre-trained model when transferring to object detection and we just follow the setup in popular SSL methods like [MoCov2.](https://github.com/facebookresearch/moco/tree/main/detection)
