### ISSUE TITLE
Fine-tuning IN pretrained models

### ISSUE THREAD

**Issue by elias-ramzi** [CupidJay/Scaled-down-self-supervised-learning#4]
Hi, 
thank you for the repository!

I had a question: did you try fine-tuning models using SSL from models initialized from Imagenet.
```
Resnet50 pretrained on Imagenet --> fine-tune with MoCo on CUB-200 --> fine-tune for classification on CUB-200
```
I hope this is clear.

Thank you for any help!
Elias

**Comment by CupidJay** [comment]
Thanks for your attention. I haven't tried this setup, but I think it's interesting and easy to implement with our code.

**Comment by elias-ramzi** [comment]
Thanks!
