### ISSUE TITLE
Training procedure on Cars196

### ISSUE THREAD

**Issue by elias-ramzi** [CupidJay/Scaled-down-self-supervised-learning#5]
Hi,

Thanks for this great repo.

I was wondering if you could share the commands to reproduce results for BYOL on cars 196. Both for a resnet18 and resnet50.

Thanks!

**Comment by CupidJay** [comment]
The settings on the Cars196 are the same as those on the CUB200.

**Comment by elias-ramzi** [comment]
Could you share the command for a ResNet18 ?
